#!/bin/bash

#
# contributed by reddtape@gmail.com
#

export CC=clang
export CXX=clang++
export MAKE_OPTS=-j2
pushd upstream
make ${MAKE_OPTS} tasks/download_binutils tasks/download_busybox tasks/download_gcc tasks/download_gcc-c++ tasks/download_gcc-core tasks/download_gcc-g77 tasks/download_newlib tasks/download_zlib
make ${MAKE_OPTS} tasks/extract_binutils tasks/extract_gcc tasks/extract_newlib
make ${MAKE_OPTS} tasks/patch_binutils tasks/patch_gcc tasks/patch_newlib
#make ${MAKE_OPTS} tasks/extract_git_classgen tasks/extract_git_gcclass
make ${MAKE_OPTS} tasks/build_git_classgen tasks/build_git_gcclass
make ${MAKE_OPTS} tasks/build_gcc
popd
make
