#define SYS_null 0
#define SYS_exit 1
#define SYS_pause 2
#define SYS_open 3
#define SYS_close 4
#define SYS_read 5
#define SYS_write 6
#define SYS_sbrk 7
#define SYS_fstat 8
#define SYS_lseek 10
#define SYS_kill 11
#define SYS_getpid 12
#define SYS_calljava 13
#define SYS_stat 14
#define SYS_gettimeofday 15
#define SYS_sleep 16
#define SYS_times 17
#define SYS_mkdir 18
#define SYS_getpagesize 19
#define SYS_unlink 20
#define SYS_utime 21
#define SYS_chdir 22
#define SYS_pipe 23
#define SYS_dup2 24
#define SYS_fork 25
#define SYS_waitpid 26
#define SYS_getcwd 27
#define SYS_exec 28
#define SYS_fcntl 29
#define SYS_rmdir 30
#define SYS_sysconf 31
#define SYS_readlink 32
#define SYS_lstat 33
#define SYS_symlink 34
#define SYS_link 35
#define SYS_getdents 36
#define SYS_memcpy 37
#define SYS_memset 38
#define SYS_dup 39
#define SYS_vfork 40
#define SYS_chroot 41
#define SYS_mknod 42
#define SYS_lchown 43
#define SYS_ftruncate 44
#define SYS_usleep 45
#define SYS_getppid 46
#define SYS_mkfifo 47
#define SYS_klogctl 51
#define SYS_realpath 52
#define SYS_sysctl 53
#define SYS_setpriority 54
#define SYS_getpriority 55
#define SYS_socket 56
#define SYS_connect 57
#define SYS_resolve_hostname 58
#define SYS_accept 59
#define SYS_setsockopt 60
#define SYS_getsockopt 61
#define SYS_listen 62
#define SYS_bind 63
#define SYS_shutdown 64
#define SYS_sendto 65
#define SYS_recvfrom 66
#define SYS_select 67
#define SYS_getuid 68
#define SYS_getgid 69
#define SYS_geteuid 70
#define SYS_getegid 71
#define SYS_getgroups 72
#define SYS_umask 73
#define SYS_chmod 74
#define SYS_fchmod 75
#define SYS_chown 76
#define SYS_fchown 77
#define SYS_access 78
#define SYS_alarm 79
#define SYS_setuid 80
#define SYS_setgid 81
#define SYS_send 82
#define SYS_recv 83
#define SYS_getsockname 84
#define SYS_getpeername 85
#define SYS_seteuid 86
#define SYS_setegid 87
#define SYS_setgroups 88
#define SYS_resolve_ip 89
#define SYS_setsid 90
#define SYS_fsync 91
